services:
  - type: web
    name: doodle-rts
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class gevent -w 1 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: SECRET_KEY
        generateValue: true
      - key: REDIS_URL
        fromService:
          type: redis
          name: doodle-rts-redis
          property: connectionString

  - type: redis
    name: doodle-rts-redis
    ipAllowList: [] # Only allow internal connections
